baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Seme Things'
theme = 'hello-friend-ng'

paginate = 10

enableRobotsTXT = false




[params]
  description = "Random stuff from a random femboy"
  author = "Alexander Fuchs"
  avatar = "images/pfp.jpg"
  bio = "I like boys"
  
  github = "https://github.com/pawbies"
  #linkedin = "https://www.linkedin.com/in/yourusername/"
  #twitter = "https://twitter.com/yourusername"

  homeSubtitle = "Random stuff from a random femboy"

  
  #custom_css = ["css/custom.css"]  # Path to your custom CSS file, if any

  
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Stories"
    url = "/stories/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3


[markup]
  [markup.highlight]
    noClasses = false


[outputs]
  home = ["HTML", "RSS", "JSON"]


[mediaTypes]
  [mediaTypes."application/rss+xml"]
    suffixes = ["xml"]

[outputFormats]
  [outputFormats.RSS]
    mediaType = "application/rss+xml"
    baseName = "index"
    isPlainText = false

[params.Logo]
  logoText = "Seme Things"